# This is a basic workflow to help you get started with Actions

name: Delete old workflow

on:
  #   push:
  #     branches: [ "main" ]
  #   pull_request:
  #     branches: [ "main" ]
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3
