name: Delete old workflow runs
on:
  workflow_dispatch:
    inputs:
      days:
        description: '天数'
        required: true
        default: 30
      minimum_runs:
        description: '为每个工作流程保留的最少运行次数'
        required: true
        default: 6
      delete_workflow_pattern:
        description: '工作流的名称或文件名。 如果未设置，则它将针对所有工作流程'
        required: false
      delete_workflow_by_state_pattern:
        description: '按状态删除工作流：活动、删除、禁用Fork、禁用不活动、禁用手动'
        required: true
        default: "All"
        type: choice
        options:
          - "All"
          - active
          - deleted
          - disabled_inactivity
          - disabled_manually
      delete_run_by_conclusion_pattern:
        description: '按结果删除工作流：需要采取的行动、已取消、失败、已跳过、成功'
        required: true
        default: "All"
        type: choice
        options:
          - "All"
          - action_required
          - cancelled
          - failure
          - skipped
          - success
      dry_run:
        description: '只做日志操作，不做任何删除操作。'
        required: false

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}
          delete_workflow_pattern: ${{ github.event.inputs.delete_workflow_pattern }}
          delete_workflow_by_state_pattern: ${{ github.event.inputs.delete_workflow_by_state_pattern }}
          delete_run_by_conclusion_pattern: ${{ github.event.inputs.delete_run_by_conclusion_pattern }}
          dry_run: ${{ github.event.inputs.dry_run }}